### ISSUE TITLE
problem converting run to xarray

### ISSUE THREAD

**Issue by gwbischof** [bluesky/intake-bluesky#26]
run_uid: fec131f6-74e9-4309-bfdb-ec500f7c1c33

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-a91cc50a1c6c> in <module>
      1 for run in latest_runs:
      2     print(run)
----> 3     a[run].primary.read()

~/conda_envs/garrett/lib/python3.7/site-packages/intake_xarray/base.py in read(self)
     38     def read(self):
     39         """Return a version of the xarray with all the data in memory"""
---> 40         self._load_metadata()
     41         return self._ds.load()
     42 

~/conda_envs/garrett/lib/python3.7/site-packages/intake/source/base.py in _load_metadata(self)
    115         """load metadata only if needed"""
    116         if self._schema is None:
--> 117             self._schema = self._get_schema()
    118             self.datashape = self._schema.datashape
    119             self.dtype = self._schema.dtype

~/conda_envs/garrett/lib/python3.7/site-packages/intake_xarray/base.py in _get_schema(self)
     17 
     18         if self._ds is None:
---> 19             self._open_dataset()
     20 
     21             metadata = {

~/dama/intake-bluesky/intake_bluesky/core.py in _open_dataset(self)
    592             get_datum_cursor=self._get_datum_cursor,
    593             include=self.include,
--> 594             exclude=self.exclude)
    595 
    596 

~/dama/intake-bluesky/intake_bluesky/core.py in documents_to_xarray(start_doc, stop_doc, descriptor_docs, event_docs, filler, get_resource, get_datum, get_datum_cursor, include, exclude)
    179             name='uid')
    180 
--> 181         datasets.append(xarray.Dataset(data_vars=data_arrays))
    182     # Merge Datasets from all Event Descriptors into one representing the
    183     # whole stream. (In the future we may simplify to one Event Descriptor

~/conda_envs/garrett/lib/python3.7/site-packages/xarray/core/dataset.py in __init__(self, data_vars, coords, attrs, compat)
    381             coords = {}
    382         if data_vars is not None or coords is not None:
--> 383             self._set_init_vars_and_dims(data_vars, coords, compat)
    384 
    385         # TODO(shoyer): expose indexes as a public argument in __init__

~/conda_envs/garrett/lib/python3.7/site-packages/xarray/core/dataset.py in _set_init_vars_and_dims(self, data_vars, coords, compat)
    403 
    404         variables, coord_names, dims = merge_data_and_coords(
--> 405             data_vars, coords, compat=compat)
    406 
    407         self._variables = variables

~/conda_envs/garrett/lib/python3.7/site-packages/xarray/core/merge.py in merge_data_and_coords(data, coords, compat, join)
    375     indexes = dict(extract_indexes(coords))
    376     return merge_core(objs, compat, join, explicit_coords=explicit_coords,
--> 377                       indexes=indexes)
    378 
    379 

~/conda_envs/garrett/lib/python3.7/site-packages/xarray/core/merge.py in merge_core(objs, compat, join, priority_arg, explicit_coords, indexes)
    443 
    444     coerced = coerce_pandas_values(objs)
--> 445     aligned = deep_align(coerced, join=join, copy=False, indexes=indexes)
    446     expanded = expand_variable_dicts(aligned)
    447 

~/conda_envs/garrett/lib/python3.7/site-packages/xarray/core/alignment.py in deep_align(objects, join, copy, indexes, exclude, raise_on_invalid)
    215 
    216     aligned = align(*targets, join=join, copy=copy, indexes=indexes,
--> 217                     exclude=exclude)
    218 
    219     for position, key, aligned_obj in zip(positions, keys, aligned):

~/conda_envs/garrett/lib/python3.7/site-packages/xarray/core/alignment.py in align(*objects, **kwargs)
    153                     'arguments without labels along dimension %r cannot be '
    154                     'aligned because they have different dimension sizes: %r'
--> 155                     % (dim, sizes))
    156 
    157     result = []

ValueError: arguments without labels along dimension 'dim_0' cannot be aligned because they have different dimension sizes: {0, 1, 2, 3, 4, 5, 7, 40, 10, 12, 20}

**Comment by gwbischof** [comment]
[xarray.txt](https://github.com/NSLS-II/intake-bluesky/files/3138925/xarray.txt)

**Comment by danielballan** [comment]
Resolved by https://github.com/bluesky/databroker/pull/438
